version: '3.8'

services:
  toolselector-mcp:
    build: .
    container_name: toolselector-mcp
    ports:
      - "3020:3020"
    environment:
      - PORT=3020
      - NODE_ENV=production
    networks:
      - letta-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3020/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  letta-network:
    external: true