services:
  frontend:
    image: ghcr.io/oculairmedia/letta-toolselector-frontend:feature-dashboard-frontend
  mcp-server:
    image: ghcr.io/oculairmedia/letta-toolselector-mcp-server:feature-dashboard-frontend
  api-server:
    image: ghcr.io/oculairmedia/letta-toolselector-api-server:feature-dashboard-frontend
  sync-service:
    image: ghcr.io/oculairmedia/letta-toolselector-sync-service:feature-dashboard-frontend
  time-service:
    image: ghcr.io/oculairmedia/letta-toolselector-api-server:feature-dashboard-frontend