#!/usr/bin/env bash
# install-hooks.sh — Install git hooks for this repo.
# Run once after cloning: bash scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_DIR="$REPO_ROOT/.git/hooks"

# Create pre-commit hook that chains repo lint + ruff + beads
cat > "$HOOK_DIR/pre-commit" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit directly.
# Re-run: bash scripts/install-hooks.sh

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# 1. Repo structure lint (check staged files only)
if [[ -f "$REPO_ROOT/scripts/lint-repo-structure.sh" ]]; then
  bash "$REPO_ROOT/scripts/lint-repo-structure.sh" --staged
fi

# 2. Ruff lint + format check (if ruff is installed)
if command -v ruff >/dev/null 2>&1; then
  echo "Running ruff check..."
  ruff check tool-selector-api/ worker-service/ tests/ scripts/ --config pyproject.toml --quiet
  echo "Running ruff format check..."
  ruff format --check tool-selector-api/ worker-service/ tests/ scripts/ --config pyproject.toml --quiet
fi

# 3. Beads hook (if bd is installed)
if command -v bd >/dev/null 2>&1; then
  bd hooks run pre-commit "$@"
fi
HOOK

chmod +x "$HOOK_DIR/pre-commit"
echo "✅ Pre-commit hook installed at $HOOK_DIR/pre-commit"
echo "   Chains: repo structure lint → ruff lint/format → beads sync"
